version: '3.4'
services:
  # Redis Image is necessary for the asyncronous scheduling in the docker application
  redis-scheduler:
    restart: always
    container_name: neontoscheduler
    image: redis
    ports:
      - '6379:6379'

  # This is the main application for the git metric aggregation
  neontometricsapi:
    restart: always
    container_name: neontometricsapi
    image: neontometrics
    # The starting of the mySQL-Database takes longer than the start up of the django webapp.

    # Wait-for-it.sh ensures that the database is up and running before starting django.
    command: "python manage.py runserver 0.0.0.0:8000"
    #command: 'python manage.py runserver 0.0.0.0:8000' 
    ports:
      - '8012:8000'
    depends_on:
      - neontometricsdb
      - migrateDB
    environment:
      db_password: 'KMmsWrwRBBeQLXDO'
      inDocker: "True"

  neontometrics_worker:
    restart: always
    image: neontometrics
    command: python manage.py rqworker
    deploy:
      replicas: 3
    depends_on:
      - neontometricsapi
      - neontometricsdb
      - migrateDB
    environment:
      db_password: 'KMmsWrwRBBeQLXDO'
      isWorker: "True"
      inDocker: "True"

  # the REST-Calculation Engine
  opi:
    ports:
      - '8082:8080'
    restart: always
    container_name: opi
    environment:
      JVM_OPTS: -Xmx12g -Xms12g -XX:MaxPermSize=2g
    build:
      context: ./Opi
    image: opi

  # The flutter Frontend
  frontend:
    ports:
      - '8003:8000'
    restart: always
    container_name: neontometricsfrontend
    build:
      context: ./frontend
    image: neontometricsfrontend

  # Creates the tables necessary in the database
  migrateDB:
    restart: "no"
    build:
      context: ./Git-Extension
    image: neontometrics
    depends_on:
      - neontometricsdb
    environment:
      db_password: 'KMmsWrwRBBeQLXDO'
      inDocker: "True"
    command: bash -c "python manage.py makemigrations rest --noinput && python manage.py migrate"

  # The Database for metric documentation
  neontometricsdb:
    restart: always
    container_name: neontometricsdb
    image: mariadb:latest
    ports:
      - '3316:3306'
    environment:
      MYSQL_DATABASE: "neontometrics"
      MYSQL_USER: "neontometrics"
      MYSQL_PASSWORD: 'KMmsWrwRBBeQLXDO'
      MYSQL_ROOT_PASSWORD: 'KMmsWrwRBBeQLXDO'
    volumes:
      - neontometricsdb:/var/lib/mysql
volumes:
  neontometricsdb:
